---
title: "Workshops"
---

We organise in-person and online workshops covering a wide range of topics such as:

- Using the Palaeoverse R packages
- Data visualisation with ggplot2
- Debugging R code
- Developing your own R packages

We have workshops designed for all experience levels, from complete beginners who are learning R for the first time, to experienced users who are looking to develop new skills.
To date, we have trained more than 150 researchers and continue to expand our training programme, with several new workshops planned from late 2026 onwards. A complete list of upcoming and past workshops can be found on our [Events page](../../events).

Teaching materials from our previous workshops are currently available to browse [here](https://workshop.palaeoverse.org/){target="_blank"}. Many of the materials from our upcoming workshops will also be available as self-paced learning resources on our Modules page, which you will be able to access at any time. We are actively developing these new modules, so be sure to check back regularly and keep an eye on our social media pages for additional content.

If you have any questions or are interested in helping us organise future workshops, please contact us at [info@palaeoverse.org](mailto:info@palaeoverse.org).
